### PR TITLE
US49806: ResourcePoolID datatype changed to interface

### PR DESCRIPTION
**Pull request by mahesh-hpe**
image

### CODE REVIEW

**Comment by mahesh-hpe** [comment]
While running Instance creation test case
image
While running Clone Instance test case
image
image

**Review by reubenur-rahman — APPROVED** [review]

**Review by manjunath-batakurki — COMMENTED** [review]
LGTM. I hope u have tested this change in a system that is 5.2.X as well. Ideally interface should work for all use-cases. so just making sure we are not missing any validations. Let me know if you need to verify this on Integ2. I can create an API client if you dont have on.

**Comment by mahesh-hpe** [comment]
Pre-pending 'pool-' when >6.0.3
image
image
image

**Review by manjunath-batakurki — APPROVED** [review]
there needs to be a release cut and should be consumed in terraform.

**Pull request merged**
